config/routes.rb
Rails.application.routes.draw do
  namespace :yandex do
    resources :banners
  end

  root "campaigns#index"

  namespace :yandex do
    resources :campaigns
    match "/create_real/:id" => "campaigns#create_real", via: :get, as: :create_real
    match "/mod_campaign/:id" => "campaigns#mod_campaign", via: :get, as: :mod_campaign
    
  end

  devise_scope :user do
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :sign_out
    get 'sign_in', :to => 'devise/sessions#new', :as => :sign_in
  end

  devise_for :users
  resources :users

  match "yandex/get_token" => 'yandex#get_token', via: :get
  match "yandex/index" => 'yandex#index', via: :get

end

app/models/campaign.rb
class Campaign 

end

app/models/yandex.rb
module Yandex
  def self.table_name_prefix
    'yandex_'
  end
end

app/models/yandex/api/direct.rb
require 'net/http'
require 'net/https'
require 'json'
require 'yaml'
require 'uri'

module Yandex
  module API
    module Direct
      URL_API = 'https://api.direct.yandex.ru/v4/json/'
      
      def self.configuration
        if defined? @environment
          raise RuntimeError.new("not configured Yandex.Direct for #{@environment} enviroment") unless @configuration
        else
          raise RuntimeError.new('not configured Yandex.Direct') unless @configuration
        end
        @configuration
      end

      def self.parse_json json
        begin
          return JSON.parse(json)
        rescue => e
          raise RuntimeError.new "#{e.message} in response"
        end
      end
      
      def self.load file, env = nil
        @environment = env if env
        config = YAML.load_file(file)
        @configuration = defined?(@environment) ? config[@environment] : config
      end

      def self.request method, params = {}

        body = {
          :locale => configuration['locale'],
          :login => configuration['login'],
          :application_id => configuration['application_id'],
          :token => configuration['token'],
          :method => method
        }
        
        body.merge!({:param => params}) unless params.empty?
        url = URI.parse(URL_API)

        if configuration['verbose']
          puts "\t\033[32mURL: \033[0m#{URL_API}"
          puts "\t\033[32mMethod: \033[0m#{method}"
          puts "\t\033[32mParams: \033[0m#{body.inspect}"  
          puts "\t\033[32mJson: \033[0m#{JSON.generate(body)}"
        end

        http = Net::HTTP.new(url.host, url.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
        response = http.post(url.path,JSON.generate(body))

        raise Yandex::API::RuntimeError.new("#{response.code} - #{response.message}") unless response.code.to_i == 200

        json = Direct.parse_json(response.body)
        
        if json.has_key?('error_code') and json.has_key?('error_str')
          code = json['error_code'].to_i
          error = json['error_detail'].length > 0 ? json['error_detail'] : json['error_str']
          raise RuntimeError.new "#{code} - #{error}"
        end
        
        return json['data']
      end
    end
  end
end

app/models/yandex/banner.rb
class Yandex::Banner < ActiveRecord::Base
  belongs_to :campaign, class_name: "Yandex::Campaign", :foreign_key => :campaign_id
  serialize :phrases, Array

  def create
    Yandex::API::Direct::request('CreateOrUpdateBanners', self.to_hash)
  end

  def to_hash
    [{"BannerID" => self.banner_id, 
     "CampaignID" => self.campaign.campaign_id,
     "Title" => self.title,
     "Text" => self.text,
     "Href" => self.href,
     "Geo" => self.geo,
     "Phrases" => Array(self.phrases.map{|p| {"Phrase" => p, "Price" => '1.1'}})
   }]
  end
end

app/models/yandex/campaign.rb
class Yandex::Campaign <  ActiveRecord::Base
  belongs_to :strategy, class_name: "Yandex::Strategy"
  belongs_to :email_notifications, class_name: "Yandex::EmailNotificationInfo"
  belongs_to :user
  has_many :banners, class_name: "Yandex::Banner"

  def create
    Yandex::API::Direct::request('CreateOrUpdateCampaign', self.to_hash)
  end

  def get_params
    Yandex::API::Direct::request('GetCampaignsParams', {"CampaignIDS" => [self.campaign_id]})
  end

  def to_moderate    
    Yandex::API::Direct::request('ModerateBanners', {"CampaignID" => self.campaign_id,
       "BannerIDS" => Array(self.banners.map{|b| b.banner_id})})
  end

  def to_hash
    {"CampaignID" => self.campaign_id,
     "Name" => self.name,
     "FIO"  => self.user.fio,
     # "StartDate" => self.start_date,
     "Strategy" => self.strategy.to_hash,
     "EmailNotification" => self.email_notifications.to_hash} 
  end
end

app/models/yandex/email_notification_info.rb
class Yandex::EmailNotificationInfo < ActiveRecord::Base

  belongs_to :campaign, class_name: "Yandex::Campaign", :foreign_key => :campaign_id

  def to_hash
    {"Email" => self.campaign.user.email,
     "MoneyWarningValue" => 2,
     "WarnPlaceInterval" => 30}
  end
end

app/models/yandex/strategy.rb
class Yandex::Strategy < ActiveRecord::Base
  StrategyNames = { "HighestPosition" => "Наивысшая доступная позиция" , 
    "LowestCost" => "Показ в блоке по минимальной цене", 
    "LowestCostPremium" => "Показ в блоке по минимальной цене",
    "WeeklyBudget" => "Недельный бюджет",
    "WeeklyPacketOfClicks" => "Недельный пакет кликов",
    "AverageClickPrice" => "Средняя цена клика",
    "NoPremiumPosition" => "Показ под результатами поиска",
    "IndependentControl" => "Независимое управление для разных типов площадок"}

  belongs_to :campaign, class_name: "Yandex::Campaign", :foreign_key => :campaign_id


  def to_hash
    {"StrategyName" => self.name,
     # "WarnPlaceInterval" => self.WarnPlaceInterval,
     # "MoneyWarningValue" => self.MoneyWarningValue}
   }
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :set_campaign, only: [:show, :edit, :update, :destroy]

  # GET /campaigns
  # GET /campaigns.json
  def index
    redirect_to "/yandex/campaigns"
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
  end

  # GET /campaigns/new
  def new
    @campaign = Campaign.new
  end

  # GET /campaigns/1/edit
  def edit
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(campaign_params)

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to @campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @campaign }
      else
        format.html { render :new }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campaigns/1
  # PATCH/PUT /campaigns/1.json
  def update
    respond_to do |format|
      if @campaign.update(campaign_params)
        format.html { redirect_to @campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @campaign }
      else
        format.html { render :edit }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign.destroy
    respond_to do |format|
      format.html { redirect_to campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campaign
      @campaign = Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campaign_params
      params.require(:campaign).permit(:user_id, :name)
    end
end

app/controllers/yandex/banners_controller.rb
class Yandex::BannersController < ApplicationController
  before_action :set_yandex_banner, only: [:show, :edit, :update, :destroy]

  # GET /yandex/banners
  # GET /yandex/banners.json
  def index
    @yandex_banners = Yandex::Banner.all
  end

  # GET /yandex/banners/1
  # GET /yandex/banners/1.json
  def show
  end

  # GET /yandex/banners/new
  def new
    @yandex_banner = Yandex::Banner.new
  end

  # GET /yandex/banners/1/edit
  def edit
  end

  # POST /yandex/banners
  # POST /yandex/banners.json
  def create
    p params

    c = Yandex::Campaign.find params[:yandex_banner][:campaign_id]
    @yandex_banner = c.banners.build(campaign_id: params[:yandex_banner][:campaign_id], text: params[:yandex_banner][:text],
      title: params[:yandex_banner][:title], href: params[:yandex_banner][:href], geo: params[:yandex_banner][:geo], banner_id: 0)
    @yandex_banner.phrases = params[:yandex_banner][:phrases].split(';')


    respond_to do |format|
      if @yandex_banner.save
        format.html { redirect_to @yandex_banner.campaign, notice: 'Banner was successfully created.' }
        format.json { render :show, status: :created, location: @yandex_banner }
      else
        format.html { render :new }
        format.json { render json: @yandex_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yandex/banners/1
  # PATCH/PUT /yandex/banners/1.json
  def update
    respond_to do |format|
      if @yandex_banner.update(yandex_banner_params)
        format.html { redirect_to @yandex_banner, notice: 'Banner was successfully updated.' }
        format.json { render :show, status: :ok, location: @yandex_banner }
      else
        format.html { render :edit }
        format.json { render json: @yandex_banner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yandex/banners/1
  # DELETE /yandex/banners/1.json
  def destroy
    @yandex_banner.destroy
    respond_to do |format|
      format.html { redirect_to yandex_banners_url, notice: 'Banner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_yandex_banner
      @yandex_banner = Yandex::Banner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yandex_banner_params
      params.require(:yandex_banner).permit(:banner_id, :campaign_id, :title, :text, :href, :geo, :phrases)
    end
end

app/controllers/yandex/campaigns_controller.rb
class Yandex::CampaignsController < ApplicationController
  before_action :set_yandex_campaign, only: [:show, :edit, :update, :destroy, :create_real, :mod_campaign]
  before_action :config_yandex, only: [:show, :create_real, :mod_campaign, :create]

  # GET /yandex/campaigns
  # GET /yandex/campaigns.json
  def index
    @yandex_campaigns = Yandex::Campaign.all
  end

  # GET /yandex/campaigns/1
  # GET /yandex/campaigns/1.json
  def show
    @status_mod = {"Yes" => "модератор одобрил хотя бы одно объявление",
        "No" => "модератор отклонил все объявления",
        "New" => "объявления не отправлялись на проверку (статус кампании «Черновик»)",
        "Pending" => "проводится проверка"}
    @params = @yandex_campaign.get_params.try(:first)
    @params = {} if @params.nil?
    p @params
  end

  # GET /yandex/campaigns/new
  def new
    @yandex_campaign = Yandex::Campaign.new
  end

  # GET /yandex/campaigns/1/edit
  def edit
  end

  # POST /yandex/campaigns
  # POST /yandex/campaigns.json
  def create
    @yandex_campaign = current_user.campaigns.build(name: params[:yandex_campaign][:name])
    @yandex_campaign.user = current_user
    @yandex_campaign.campaign_id = 0

    str = @yandex_campaign.build_strategy(name: params[:yandex_campaign][:strategy_name])
    str.campaign = @yandex_campaign
    str.save!

    email_n = @yandex_campaign.build_email_notifications
    email_n.campaign = @yandex_campaign
    email_n.save!

    id = @yandex_campaign.create
    @yandex_campaign.campaign_id = id
    @yandex_campaign.save

    respond_to do |format|
      if @yandex_campaign.save
        format.html { redirect_to @yandex_campaign, notice: 'Campaign was successfully created.' }
        format.json { render :show, status: :created, location: @yandex_campaign }
      else
        format.html { render :new }
        format.json { render json: @yandex_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /yandex/campaigns/1
  # PATCH/PUT /yandex/campaigns/1.json
  def update
    respond_to do |format|
      if @yandex_campaign.update(yandex_campaign_params)
        format.html { redirect_to @yandex_campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @yandex_campaign }
      else
        format.html { render :edit }
        format.json { render json: @yandex_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yandex/campaigns/1
  # DELETE /yandex/campaigns/1.json
  def destroy
    @yandex_campaign.destroy
    respond_to do |format|
      format.html { redirect_to yandex_campaigns_url, notice: 'Campaign was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def create_real



    @yandex_campaign.banners.each do |b|
      id = b.create
      b.banner_id = id.first
      b.save!
    end

    respond_to do |format|
      if @yandex_campaign.save
        format.html { redirect_to @yandex_campaign, notice: 'Campaign was successfully updated.' }
        format.json { render :show, status: :ok, location: @yandex_campaign }
      else
        format.html { render :edit }
        format.json { render json: @yandex_campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  def mod_campaign
    id = @yandex_campaign.to_moderate

    redirect_to @yandex_campaign, notice: 'Кампания отправлена на модерацию.'
  end

  private
    def config_yandex
      Yandex::API::Direct.load File.join(Rails.root,"config","yandex_direct.yml"), Rails.env
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_yandex_campaign
      @yandex_campaign = Yandex::Campaign.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def yandex_campaign_params
      params.require(:yandex_campaign).permit(:name, :strategy_name)
    end
end

app/controllers/yandex_controller.rb
class YandexController < ApplicationController
  def get_token
    require 'net/http'
    require 'net/https'
    require 'json'
    require 'uri'
    Yandex::API::Direct.load File.join(Rails.root,"config","yandex_direct.yml"), Rails.env

    url = URI.parse("https://oauth.yandex.ru/token")

    body = {
      :grant_type => "???",
      :code => params[:code],
      :client_id => Yandex::API::Direct.configuration['application_id'],
      :client_secret => Yandex::API::Direct.configuration['client_secret']
    }

    http = Net::HTTP.new(url.host, url.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    response = http.post(url.path,JSON.generate(body))

    parsed = JSON.parse(response)

    render json: "ok"
  end

  def index
    Yandex::API::Direct.load File.join(Rails.root,"config","yandex_direct.yml"), Rails.env
    redirect_to "https://oauth.yandex.ru/authorize?response_type=code&client_id=#{Yandex::API::Direct.configuration['application_id']}"
  end
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/yandex/banners_helper.rb
module Yandex::BannersHelper
end

app/helpers/yandex/campaigns_helper.rb
module Yandex::CampaignsHelper
end

app/views/yandex/campaigns/_form.html.haml
.form-group.well
  = form_for(@yandex_campaign) do |f|
    - if @yandex_campaign.errors.any?
      #error_explanation
        %h2
          = pluralize(@yandex_campaign.errors.count, "error")
          prohibited this yandex_campaign from being saved:
        %ul
          - @yandex_campaign.errors.full_messages.each do |message|
            %li= message
    .field
      = f.label "Имя"
      %br/
      = f.text_field :name, class: "form-control"
    .field
      = f.label "Стратегия"
      %br/
      = f.text_field :strategy_name, value: "HighestPosition", class: "form-control"

    %br
    .actions
      = f.submit "Сохранить", class: "btn btn-success"

app/views/yandex/campaigns/edit.html.erb
<h1>Editing yandex_campaign</h1>

<%= render 'form' %>

<%= link_to 'Show', @yandex_campaign %> |
<%= link_to 'Back', yandex_campaigns_path %>

app/views/yandex/campaigns/index.html.erb
<h1>Listing yandex_campaigns</h1>

<table>
  <thead>
    <tr>
      <th>Strategy</th>
      <th>Email notifications</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @yandex_campaigns.each do |yandex_campaign| %>
      <tr>
        <td><%= yandex_campaign.strategy %></td>
        <td><%= yandex_campaign.email_notifications %></td>
        <td><%= link_to 'Show', yandex_campaign %></td>
        <td><%= link_to 'Edit', edit_yandex_campaign_path(yandex_campaign) %></td>
        <td><%= link_to 'Destroy', yandex_campaign, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campaign', new_yandex_campaign_path %>

app/views/yandex/campaigns/index.html.haml
%h1 Список кампаний
%table.table.table-hover
  %thead
    %tr
      %th id
      %th id (Yandex)
      %th Имя
      %th Стратегия
      %th{:colspan => "3"}
  %tbody
    - @yandex_campaigns.each do |yandex_campaign|
      %tr
        %td= yandex_campaign.id
        %td= yandex_campaign.campaign_id
        %td= yandex_campaign.name
        %td= Yandex::Strategy::StrategyNames[yandex_campaign.strategy.try(:name)]
        %td= link_to 'Edit', edit_yandex_campaign_path(yandex_campaign)
        %td= link_to 'Show', yandex_campaign
        %td= link_to 'Destroy', yandex_campaign, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'Новая кампания', new_yandex_campaign_path, class: "btn btn-success"

app/views/yandex/campaigns/new.html.erb
<h1>New yandex_campaign</h1>

<%= render 'form' %>

<%= link_to 'Back', yandex_campaigns_path %>

app/views/yandex/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Strategy:</strong>
  <%= @yandex_campaign.strategy %>
</p>

<p>
  <strong>Email notifications:</strong>
  <%= @yandex_campaign.email_notifications %>
</p>

<%= link_to 'Edit', edit_yandex_campaign_path(@yandex_campaign) %> |
<%= link_to 'Back', yandex_campaigns_path %>

app/views/yandex/campaigns/show.html.haml
%p#notice= notice
%p Информация
%table.table.table-bordered
  %thead
    %tr
      %th id
      %th id (Yandex)
      %th Имя
      %th Стратегия
      %th Статус
      %th Активность 
      %th Модерация
      %th{:colspan => "2"}
  %tbody
    %tr
      %td= @yandex_campaign.id
      %td= @yandex_campaign.campaign_id
      %td= @yandex_campaign.name
      %td= Yandex::Strategy::StrategyNames[@yandex_campaign.strategy.try(:name)]
      %td= @params['Status']
      %td= @params['IsActive']
      %td= @status_mod[@params['StatusModerate']]
      %td= link_to 'Edit', edit_yandex_campaign_path(@yandex_campaign)
      %td= link_to 'Destroy', @yandex_campaign, method: :delete, data: { confirm: 'Are you sure?' }
%p Статистика
%table.table.table-bordered
  %thead
    %tr
      %th Текущий баланс общего счета
      %th Показы за все время
      %th Клики за все время

  %tbody
    %tr
      %td= @params['Rest']
      %td= @params['Shows']
      %td= @params['Clicks']

%p Объявления

%table.table.table-bordered
  %thead
    %tr
      %th id
      %th id (Yandex)
      %th Заголовок
      %th Текст
      %th Фразы
      %th Ссылка 
      %th{:colspan => "3"}
  %tbody
    -@yandex_campaign.banners.each do |b|
      %tr
        %td= b.id
        %td= b.banner_id
        %td= b.title
        %td= b.text
        %td= b.phrases
        %td= b.href
        %td= link_to 'Edit', edit_yandex_banner_path(b)
        %td= link_to 'Destroy', b, method: :delete, data: { confirm: 'Are you sure?' }
        %td=# link_to 'Запрос', yandex_create_real_path(@yandex_campaign), class: "btn btn-primary"

= link_to 'Новое объявление', new_yandex_banner_path(campaign_id: @yandex_campaign.id), class: "btn btn-success"
%br
%br
= link_to 'Отправить данные на Yandex.Direct', yandex_create_real_path(@yandex_campaign), class: "btn btn-primary"
= link_to 'Отправить на модерацию', yandex_mod_campaign_path(@yandex_campaign), class: "btn btn-primary"

%br
%br




= link_to 'Edit', edit_yandex_campaign_path(@yandex_campaign)
|
\#{link_to 'Back', yandex_campaigns_path}